apiVersion: v1
kind: Secret
# the weatherapp-weather helm chart requires the APIKEY. This defaines where it will be stored and how it will be processed
metadata:
    name: {{ .Release.Name }}
type: Opaque
data:
    apikey: {{ .Values.apikey | b64enc | quote }}
    # the value will be from the command line with the --set flag. Putting it in values.yaml is insecure.
    # once gitlab pipeline is configured the command line args for secrets can be securely stored in gitlab